### ISSUE TITLE
lgs.osm not auto-loading into the game/DromEd

### ISSUE THREAD

**Issue by sunbeam906** [whoopdedo/lgscript#1]
Hi there,

Am currently doing some reverse engineering of my own with the NewDark 2.48 version of SS2. While working out the ShockGameSrv vftable, I used a DromEd version with debug symbols leading me to various function names and structures. Stumbled across your lgscript and wanted to give it a spin. DromEd doesn't load it by default (yes, it's placed in game folder) and injecting it manually doesn't spawn any thread/listener that would pick-up on the .lua scripts.

If you're reading this after oh-so-many years, gimme a bump :)

Cheers,
Sun

**Comment by whoopdedo** [comment]
`lgs.osm` goes in the script module load path. Your Lua scripts go in the `scripts` folder. Changes to the Lua scripts don't get auto-loaded I'm afraid. You have to unload then reload the LGS module to make that happen. Although Dromed tends to do that anyway when changing between game and edit mode.

**Comment by sunbeam906** [comment]
"lgs.osm goes in the script module load path." -- this is the main folder of the game where the other .osm file are. I put it there and nada, neither the game or DromEd loads it by default. Like I said, I also injected it manually and no go.

![image](https://user-images.githubusercontent.com/148178/188355061-a43137c6-0ec4-4428-8fd9-a1af4e9f7c21.png)

I understood the part with Lua changes not happening in real-time, no worries there.

**Comment by sunbeam906** [comment]
And here's DromEd open with miss1.osm loaded and no lgs.osm among the loaded modules:

![image](https://user-images.githubusercontent.com/148178/188355484-2d9c56e1-d86f-4f5a-96be-3f95a5c7a99a.png)

So unless I'm doing something wrong or I have to define a line or something in a .cfg file, then I dunno.

Cheers,
Sun

**Comment by sunbeam906** [comment]
..or was this never supposed to auto-load with DromEd loading a .mis file? So..

![image](https://user-images.githubusercontent.com/148178/188356777-835912aa-cb64-45d3-a710-a85e0b9189f5.png)

Cheers,
Sun

**Comment by whoopdedo** [comment]
Correct. Script modules must be assigned to a mission. The Dromed command `script_dump_files` will list the OSMs in use.
