### ISSUE TITLE
files missing from the source code

### ISSUE THREAD

**Issue by sunbeam906** [whoopdedo/lgscript#2]
Hi again,

Attempted to compile this on my own with debug symbols, so I can see what's going on. Noticed you've omitted some files from the lot:

#include <lg/config.h>
#include <lg/objstd.h>
#include <lg/interfaceimp.h>
#include <lg/script.h>
#include <lg/scrmsgs.h>
etc.

I understand this is part of the old leaked source code? :)

Best regards,
Sun

**Comment by whoopdedo** [comment]
The build setup uses multiple repositories. The `lg` repository has the common headers for all scripts. I don't use leaked source code.

https://github.com/whoopdedo/lg
https://github.com/whoopdedo/scriptlib (not used by lgscript)
https://github.com/whoopdedo/dh2

Clone those and this repository into a project tree as such

\\ Project
|- lg
|- dh2
|- scriptlib
|- dh2
|- lgscript

Then build each in that order. Keep in mind it's been a very long time so I can't even guess what will happen in today's MinGW environment. It may work, but don't be surprised to see a lot of warnings and possibly errors.
